### ISSUE TITLE
Teensyduino 1.60.0 breaks MTP on Teensy 3.6

### ISSUE THREAD

**Issue by jrw429** [PaulStoffregen/cores#801]
Teensyduino 1.60.0 has rolled support for MTP into the core. As part of this, there is a new Basic_SD_Card example. This example compiles and runs on Teensy 4.1. It fails to compile on Teensy 3.6, with error: "'MTP' was not declared in this scope".

For years I had been using MTP by cloning https://github.com/KurtE/MTP_Teensy into my libraries directory. I didn't realize until today that 1.60.0 includes MTP and thus ought to supersede that. If I compile my Teensy 3.6 code with the old MTP library, it will run but after 78 seconds all input or output to USB serial stops. The Teensy continues to run and control peripherals. This worked with 1.59.0 and previous versions.
